## Pandas 데이터 프레임

### 데이터 불러오기

In [2]:
import pandas as pd
from sklearn.datasets import load_iris

In [4]:
iris=load_iris()
print(iris.feature_names)
print(iris.data)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3

In [5]:
print(iris.target_names)
print(iris.target)

['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
type(iris.data)

numpy.ndarray

In [8]:
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [9]:
df['species']=iris.target

In [10]:
df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [11]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='object')

In [12]:
df.columns=['sl','sw','pl','pw','sp']

In [14]:
df.head(5)

sl   sw   pl   pw  sp
0  5.1  3.5  1.4  0.2   0
1  4.9  3.0  1.4  0.2   0
2  4.7  3.2  1.3  0.2   0
3  4.6  3.1  1.5  0.2   0
4  5.0  3.6  1.4  0.2   0

In [15]:
df.rename(columns={'sp':'s'}, inplace=True)

In [16]:
#상단 3개 출력
df.head(3)

sl   sw   pl   pw  s
0  5.1  3.5  1.4  0.2  0
1  4.9  3.0  1.4  0.2  0
2  4.7  3.2  1.3  0.2  0

In [17]:
#0부터 3까지 행 출력
df[0:4]

sl   sw   pl   pw  s
0  5.1  3.5  1.4  0.2  0
1  4.9  3.0  1.4  0.2  0
2  4.7  3.2  1.3  0.2  0
3  4.6  3.1  1.5  0.2  0

In [18]:
#15번째 행 출력
df[15:16]

sl   sw   pl   pw  s
15  5.7  4.4  1.5  0.4  0

In [20]:
#sl, pw열 출력
df[['sl','pw']]

sl   pw
0    5.1  0.2
1    4.9  0.2
2    4.7  0.2
3    4.6  0.2
4    5.0  0.2
..   ...  ...
145  6.7  2.3
146  6.3  1.9
147  6.5  2.0
148  6.2  2.3
149  5.9  1.8

[150 rows x 2 columns]

In [22]:
#0부터 3까지 중에 sl, s열만 출력
df[0:4][['sl','s']]

sl  s
0  5.1  0
1  4.9  0
2  4.7  0
3  4.6  0

In [23]:
#df데이터 프레임의 데이터 확인
df.values

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [24]:
#df데이터 프레임의 열 인덱스 확인
df.columns

Index(['sl', 'sw', 'pl', 'pw', 's'], dtype='object')

In [25]:
#df데이터프레임의 행 인덱스 확인
df.index

RangeIndex(start=0, stop=150, step=1)

In [26]:
#0부터 3번째 행까지 sl,s열 데이터만 불러오기
df.loc[0:3,('sl','s')]

sl  s
0  5.1  0
1  4.9  0
2  4.7  0
3  4.6  0

In [29]:
#3번째 행까지 sl,pw열 데이터만 불러오기
df.iloc[0:4,[0,3]]

sl   pw
0  5.1  0.2
1  4.9  0.2
2  4.7  0.2
3  4.6  0.2

In [30]:
#df데이터 셋에서 컬럼s가 1인 대상만 추출해서 df_1에 넣음
df_1=df[df.s==1]

In [31]:
#데이터프레임의 경우 info() 함수를 이용해 데이터 셋 정보 확인 가능
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 50 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   sl      50 non-null     float64
 1   sw      50 non-null     float64
 2   pl      50 non-null     float64
 3   pw      50 non-null     float64
 4   s       50 non-null     int32  
dtypes: float64(4), int32(1)
memory usage: 2.1 KB


In [32]:
#tail()함수를 이용해 끝에서부터 위로 원하는 행만큼 조회 가능 (head반대)
df_1.tail(5)

sl   sw   pl   pw  s
95  5.7  3.0  4.2  1.2  1
96  5.7  2.9  4.2  1.3  1
97  6.2  2.9  4.3  1.3  1
98  5.1  2.5  3.0  1.1  1
99  5.7  2.8  4.1  1.3  1

In [35]:
#df데이터 셋에서 sl이 6보다 크고 s가 1인 대상만 추출해 df_2에 넣음
df_2=df[(df.sl>6)&(df.s==1)]
df_2

sl   sw   pl   pw  s
50  7.0  3.2  4.7  1.4  1
51  6.4  3.2  4.5  1.5  1
52  6.9  3.1  4.9  1.5  1
54  6.5  2.8  4.6  1.5  1
56  6.3  3.3  4.7  1.6  1
58  6.6  2.9  4.6  1.3  1
63  6.1  2.9  4.7  1.4  1
65  6.7  3.1  4.4  1.4  1
68  6.2  2.2  4.5  1.5  1
71  6.1  2.8  4.0  1.3  1
72  6.3  2.5  4.9  1.5  1
73  6.1  2.8  4.7  1.2  1
74  6.4  2.9  4.3  1.3  1
75  6.6  3.0  4.4  1.4  1
76  6.8  2.8  4.8  1.4  1
77  6.7  3.0  5.0  1.7  1
86  6.7  3.1  4.7  1.5  1
87  6.3  2.3  4.4  1.3  1
91  6.1  3.0  4.6  1.4  1
97  6.2  2.9  4.3  1.3  1

In [39]:
#df데이터 셋에서 s가 0인 대상의 sl,sw,s열만 추출해 df_3에 넣음
df_3=df.loc[df.s==0,['sl','sw','s']]
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   sl      50 non-null     float64
 1   sw      50 non-null     float64
 2   s       50 non-null     int32  
dtypes: float64(2), int32(1)
memory usage: 1.4 KB


In [42]:
#df데이터 셋에서 s열만 제외하고 추출해 df_4에 넣음
df_4=df[df.columns.difference(['s'])]
df_4.head(5)

pl   pw   sl   sw
0  1.4  0.2  5.1  3.5
1  1.4  0.2  4.9  3.0
2  1.3  0.2  4.7  3.2
3  1.5  0.2  4.6  3.1
4  1.4  0.2  5.0  3.6

# numpy의 다차원 배열

In [43]:
#numpy 패키지 불러오기 및 np라는 약어로 지칭
import numpy as np

In [44]:
#스칼라
a0=np.array(1)
a0

array(1)

In [45]:
#벡터
a1=np.array([1,2])
a1

array([1, 2])

In [49]:
#행렬
a2=np.array([[1,2],[3,4]])
a2

array([[1, 2],
       [3, 4]])

In [52]:
#텐서
a3=np.array([[[1,2,3],
             [4,5,6]],
             [[7,8,9],
              [2,4,8]]])
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 4, 8]]])

In [53]:
#ndim 속성을 이용해 배열의 차원 확인
print(a0.ndim,a1.ndim,a2.ndim,a3.ndim)

0 1 2 3


In [54]:
#shape 속성을 이용해 배열의 크기 확인
print(a0.shape,a1.shape,a2.shape,a3.shape)

() (2,) (2, 2) (2, 2, 3)


### 다차원 배열 다루기

In [56]:
#3차원 배열에서 1번째 행렬 필터링
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
#3차원 배열에서 1번째 행렬의 2번째 행 필터링
a3[0,1]

array([4, 5, 6])

In [58]:
#3차원 배열에서 1번째 행렬의 2번째 행의 3번째 열 필터링
a3[0,1,2]

6